export const GET_ALL_ACCOUNT = '/accounts'
export const CREATE_ACCOUNT = '/accounts'
export const GET_ALL_SOCIAL_ACCOUNT = '/accounts'
// export const CREATE_SOCIAL_ACCOUNT = '/social-accounts'
// export const DELETE_USER_SOCIAL_ACCOUNT = '/social-accounts/'
// export const EDIT_USER_SOCIAL_ACCOUNT = '/social-accounts/'
export const DELETE_USER_ACCOUNT = '/accounts/'
export const EDIT_USER_ACCOUNT = '/accounts/'
